- name: generate client config
  template: src={{ item }} dest=/{{ item | dirname }}/config.jsonc owner=root group=root mode="0644"
  with_items:
    - usr/local/etc/xray/client.jsonc.j2
  notify: restart xray
  tags:
    - config

- name: increase open file limit
  pam_limits:
    domain: '*'
    limit_type: '{{ item.type }}'
    limit_item: '{{ item.item }}'
    value: '{{ item.value }}'
  with_items:
    - { type: soft, item: nofile, value: 100000 }
    - { type: hard, item: nofile, value: 100000 }
  tags:
    - config

- name: include xray transparent proxy setting
  import_tasks: xray-tproxy.yml
