# If xray is running inside LXC container, we should setup kernel module loading
# on host system instead of inside container.
# Put host name inside "lxc_container" group in ansible inventory to mark this.
- include_tasks: kernel-module.yml
  when: "'xray' in group_names and 'lxc_container' not in group_names"

- meta: end_host
  when: "'pve_host' in group_names"

- name: check if release is already downloaded
  stat: path="{{ role_path }}/files/release/Xray-{{ xray_os_arch }}-{{ xray_version }}.zip"
  register: release_check
  delegate_to: localhost
  become: no
  tags:
    - localhost

- name: download release
  shell: "{{ role_path }}/scripts/download-xray.sh {{ xray_version }}"
  delegate_to: localhost
  when: not release_check.stat.exists
  become: no
  tags:
    - localhost

- name: update geodata
  shell: "{{ role_path }}/scripts/download-geodata.sh"
  delegate_to: localhost
  become: no
  when: "'xray_server' not in group_names"
  tags:
    - update
    - never

- name: create install directories
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /usr/local/share/xray
    - /usr/local/etc/xray

- name: install xray geoip data
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=root group=root
  with_items:
    - { src: release/geoip.dat, dest: /usr/local/share/xray/geoip.dat, mode: "0644" }
    - { src: release/geosite.dat, dest: /usr/local/share/xray/geosite.dat, mode: "0644" }

- name: install xray
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=root group=root
  with_items:
    - { src: release/xray, dest: /usr/local/bin/xray, mode: "0755" }
    - { src: xray.service, dest: /etc/systemd/system/xray.service, mode: "0644" }
    - { src: xray@.service, dest: /etc/systemd/system/xray@.service, mode: "0644" }
    - { src: journald@xray.conf, dest: /etc/systemd/journald@xray.conf, mode: "0644" }
  notify: restart xray

- name: enable systemd service
  systemd: name={{ item }} enabled=yes
  with_items:
    - xray

- include_tasks: client.yml
  when: "'xray' in group_names"

- include_tasks: server.yml
  when: "'xray_server' in group_names"
