- name: generate server config
  template: src={{ item }} dest=/{{ item | dirname }}/config.jsonc owner=root group=root mode="0644"
  with_items:
    - usr/local/etc/xray/server.jsonc.j2
  notify: restart xray
  tags:
    - config
